name: CI

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults,jorgegarciairazabal
          show-channel-urls: true
          python-version: ${{ matrix.python-version }}
          activate-environment: "test"

      - name: Install senv
        shell: bash -l {0}
        run: |
          conda install senv==0.0.0a1 poetry==1.1.12 -y
          echo "Poetry path"
          echo $(which poetry)
          echo "senv path"
          echo $(which senv)

      - name: Install Dependencies
        shell: bash -l {0}
        run: senv env sync

#      - name: Code Quality
#        shell: bash -l {0}
#        run: |
#          senv env run black . --check

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          export SENVX_INSTALLATION_PATH=$HOME/.senvx/tools
          echo $SENVX_INSTALLATION_PATH
          senv env run pytest senv --junit-xml pytest.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: pytest.xml

      - name: Publish to pypi and anaconda
        shell: bash -l {0}
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          senv package publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} -b --build-system poetry -y
          senv package publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} -b --build-system conda -y
#
#      - name: Publish locked version
#        shell: bash -l {0}
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          senv package publish-locked --lock-file package_locked.lock.json

